services:
  - type: web
    name: link-rule-flask-app
    env: docker
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: "20f796e58e3bc4d40f2a9c27fd5d9d40"
    branches: 
      - main
